webserver:
  build: .
  dockerfile: Dockerfile-webserver
  ports:
    - "8000:80"
  links:
    - appserver:node
    - botserver:bot

appserver:
  build: .
  dockerfile: Dockerfile-nodejs
  ports:
    - "3000"
  volumes:
    - "./app:/app"
  command: pm2 --no-daemon start /app/ecosystem.json

botserver:
  build: .
  dockerfile: Dockerfile-hubot
  volumes:
    - "./bot:/bot"
  ports:
    - "4000"
  command: pm2 --no-daemon start /bot/ecosystem.json
